### ISSUE TITLE
Multiple clear icons displayed in IE11

### ISSUE THREAD

**Issue by ryan76** [carbon-design-system/carbon-addons-beta-react#11]
Steps to reproduce:
1) Click on the Typeahead to give it focus
2) Type some text

Result:
The Typeahead input displays an "X" icon to the left of the close icon.

Expected behavior:
After completing the steps above, only the close icon is displayed

Note:
If you click anywhere to remove focus from the Typeahead component, the "X" goes away

![multiple-clear-icons](https://user-images.githubusercontent.com/3375289/32065807-6c92ac04-ba43-11e7-9cf8-da7ed5580f0e.png)

**Comment by joshblack** [comment]
Thankfully this one is easy, seems like IE10+ adds a pseudo elements called `-ms-clear` that we can use to visually remove this element. Will definitely add this in with #9 👍
