### ISSUE TITLE
Question: when will this be part of the main react-components package?

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-addons-beta-react#15]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.

**Comment by tw15egan** [comment]
Could you please elaborate?

**Comment by dcostantino** [comment]
When will this component be out of beta and in the https://github.com/carbon-design-system/carbon-components-react git respository
