### ISSUE TITLE
scss processing error

### ISSUE THREAD

**Issue by dcostantino** [carbon-design-system/carbon-addons-beta-react#16]
I have added this line to my package.json:
"build-css": "node-sass --include-path node_modules node_modules/carbon-addons-beta-react/scss --output src/css"

when I run  npm run build-css

I am getting this error:

{
  "status": 1,
  "file": "/Users/dcostant/Documents/ResourceGroupManager/node_modules/carbon-addons-beta-react/scss/components/Typeahead/_typeahead.scss",
  "line": 36,
  "column": 14,
  "message": "no mixin named button-reset\n\nBacktrace:\n\tnode_modules/carbon-addons-beta-react/scss/components/Typeahead/_typeahead.scss:36, in mixin `@content`\n\tnode_modules/carbon-components/scss/globals/scss/_import-once.scss:12, in mixin `exports`\n\tnode_modules/carbon-addons-beta-react/scss/components/Typeahead/_typeahead.scss:6",
  "formatted": "Error: no mixin named button-reset\n\n       Backtrace:\n       \tnode_modules/carbon-addons-beta-react/scss/components/Typeahead/_typeahead.scss:36, in mixin `@content`\n       \tnode_modules/carbon-components/scss/globals/scss/_import-once.scss:12, in mixin `exports`\n       \tnode_modules/carbon-addons-beta-react/scss/components/Typeahead/_typeahead.scss:6\n        on line 36 of node_modules/carbon-addons-beta-react/scss/components/Typeahead/_typeahead.scss\n>>     @include button-reset(false);\n   -------------^\n"
}

Am I missing something?

**Comment by tw15egan** [comment]
Are you also importing the base `carbon-component` styles?

**Comment by dcostantino** [comment]
Yes, the base types are imported, I made a few changes to include additional imports and changed the buttonreset include and it compiled. I also made another small change to prevent the dropdown from overlapping what was below it.

![image](https://user-images.githubusercontent.com/22599308/33391061-de4d6c8a-d505-11e7-835f-e999c91ccb5d.png)

**Comment by tw15egan** [comment]
Great! Any way you could create a PR to add this changes to the repo as well so others don't run into this issue?
