### ISSUE TITLE
A11Y: Clear button don't have an associated label 

### ISSUE THREAD

**Issue by shijinupc** [carbon-design-system/carbon-addons-beta-react#21]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?
A general issue

> Is this issue related to a specific component?
yes

> What did you expect to happen? What happened instead? What would you like to see changed?
clear button have an associated label

> What browser are you working in?
Chrome

## Additional information
<img width="880" alt="e3376678-eb18-11e7-83bc-e9c1eb743a49" src="https://user-images.githubusercontent.com/8380554/35209377-8e86502e-ff88-11e7-8a54-87ad29d6c252.png">

**Comment by marijohannessen** [comment]
Hi @ashpc . This `TypeAhead` component was released as a beta component only, and has been replaced with the official component `MultiSelect` (found here https://github.com/carbon-design-system/carbon-components-react/tree/master/src/components/MultiSelect). This component is not to be used by any production teams so I am closing this issue. Thank you!
